export const result = {
  data: {
    data: {
      total: 76,
      totalitem: 107,
      items: [
        {
          comment_id: "38384619",
          parent_id: "38384619",
          article_id: 4219024,
          content: "Hãy tỉnh lại đi. Bạn bị em trai nào đó trêu rồi.",
          full_name: "Lê Thanh",
          creation_time: 1610327996,
          time: "7h trước",
          userlike: 613,
          replys: { total: 19, items: [] },
          userid: null,
          type: 4,
          like_ismember: false,
        },
        {
          comment_id: "38384616",
          parent_id: "38384616",
          article_id: 4219024,
          content: "Hậu quả của việc nghiện game ghê gớm quá các bác ạ...",
          full_name: "Ben",
          creation_time: 1610327991,
          time: "7h trước",
          userlike: 312,
          replys: { total: 3, items: [] },
          userid: 1049099077,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384787",
          parent_id: "38384787",
          article_id: 4219024,
          content:
            "Cách đây hơn 15 năm khi game VLTK mới xuất hiện ở Vietnam đã nhanh chóng tạo ra một cộng đồng người chơi đông đảo, bạn tôi cũng là một con nghiện của dòng game này,vì nó có ngoại hình hơi mũm mỉm nên ngại giao tiếp bên ngoài, mới chơi được vài tháng nó khoe đã có bạn gái trong game và cùng nhau lên Hoa sơn luyện kiếm và tâm sự,điều nó đau khổ là bạn gái không chịu chat yahoo cam với nó. Đến một ngày nó buồn buồn nói với tôi rằng nó đã chia tay bạn gái vì lý do bạn đó cũng mũm mỉm giống nó và càng kỳ lạ hơn là còn tiểu đứng giống nó luôn, ôi mối tình phi giới tính trong game.",
          full_name: "Tèo",
          creation_time: 1610328845,
          time: "7h trước",
          userlike: 296,
          replys: { total: 5, items: [] },
          userid: null,
          type: 4,
          like_ismember: false,
        },
        {
          comment_id: "38384948",
          parent_id: "38384948",
          article_id: 4219024,
          content: 'Bạn này "sống ảo" quá',
          full_name: "d15vb2.b1",
          creation_time: 1610329498,
          time: "7h trước",
          userlike: 98,
          replys: { total: 2, items: [] },
          userid: 1060070229,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384586",
          parent_id: "38384586",
          article_id: 4219024,
          content: "Đọc đoạn đầu là hiểu luôn :))))",
          full_name: "Xế quèn",
          creation_time: 1610327857,
          time: "7h trước",
          userlike: 85,
          replys: {},
          userid: 1043105982,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384640",
          parent_id: "38384640",
          article_id: 4219024,
          content:
            "Hơn 10 năm trước, ông anh trai của tui mặc dù đã có vợ nhưng vẫn tạo nick giả làm phụ nữ để cho trai tán tỉnh. Ổng giả gái giỏi đến mức không một anh chàng nào biết mình đang chát với một ông già ngoài 40t luôn. Haha...tác giả đúng là sống ảo quá ảo. Nghĩ sao đem lòng yêu một cô gái suốt 10 năm chỉ thông qua những tin nhắn vậy trời?",
          full_name: "Punarvasu",
          creation_time: 1610328122,
          time: "7h trước",
          userlike: 59,
          replys: {},
          userid: 1057669227,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384924",
          parent_id: "38384924",
          article_id: 4219024,
          content:
            "Khả năng, người bạn đang yêu không khéo lại là con trai giả danh con gái đó bạn :D. Thôi bỏ đi bạn, sống thực tế đi, chứ 10 năm mà ôm mộng ảo vậy, quá đủ rồi bạn.",
          full_name: "Xuân Thanh",
          creation_time: 1610329411,
          time: "7h trước",
          userlike: 52,
          replys: {},
          userid: 1055635975,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384762",
          parent_id: "38384762",
          article_id: 4219024,
          content:
            'Bạn cẩn thận nha, coi chừng "cô gái" của bạn cũng là đàn ông đấy.<br/>Mấy cái game online ấy mà, rất nhiều nữ lấy nhân vật là nam và nam thì lấy nhân vật nữ đó, nên người ta ko có nhu cầu gặp bạn đâu, mà bạn còn tính cả chuyện cưới hỏi lập gia đình sao.<br/>Xưa tui chơi VLTK í, tui có cả tk Nga My lẫn Thiếu lâm đó :P',
          full_name: "Dế Mèn",
          creation_time: 1610328746,
          time: "7h trước",
          userlike: 45,
          replys: {},
          userid: 1002624866,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384942",
          parent_id: "38384942",
          article_id: 4219024,
          content:
            "Chà, bạn quả là ng đàn ô chung tình hiếm có đấy. Tiếc là sự chung tình của bạn lại đặt nhầm vào đối tượng chim trời cá nước. Thôi, hãy dẹp bỏ những ngây thơ thời vụng dại ấy đi mà tập trung vào những chân tình ngay cạnh mình bạn nhé.",
          full_name: "Nguyễn thị kim liên",
          creation_time: 1610329472,
          time: "7h trước",
          userlike: 32,
          replys: {},
          userid: 1043295509,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384887",
          parent_id: "38384887",
          article_id: 4219024,
          content:
            "Mơ gì lâu dữ vậy ông? Người ta lấy chồng mấy con rồi mà ông vẫn chưa thức dậy sao?",
          full_name: "Trang dang",
          creation_time: 1610329274,
          time: "7h trước",
          userlike: 27,
          replys: { total: 1, items: [] },
          userid: 1032237631,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384655",
          parent_id: "38384655",
          article_id: 4219024,
          content:
            "Đầu game bên kia là một nam nhân, râu ria rậm rạp, áo quần bảnh bao nên người ta ngại không gặp thôi bạn.",
          full_name: "Nguyễn Tấn Hoàng Vũ",
          creation_time: 1610328165,
          time: "7h trước",
          userlike: 25,
          replys: {},
          userid: 1002913997,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384797",
          parent_id: "38384797",
          article_id: 4219024,
          content:
            "Bạn không những ngây thơ mà còn mù quáng, dại dột. Tôi tưởng chỉ có mấy bạn nữ cuồng phim Hàn mới mộng tưởng cuồng yêu 1 hình tượng như vậy thôi chứ. Bạn thử nghĩ xem biết đâu người con gái bạn yêu có khi có chồng con rồi cũng nên. Gặp nhau yêu nhau, ở chung còn chưa hiểu nhau rồi chia tay cơ mà. Tỉnh lại đi bạn, mở lòng, tìm đối tượng khác thực tế hơn mà yêu.",
          full_name: "Strong Trinh",
          creation_time: 1610328880,
          time: "7h trước",
          userlike: 21,
          replys: {},
          userid: 1043415233,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385329",
          parent_id: "38385329",
          article_id: 4219024,
          content:
            "Xóm tôi cũng có bạn nữ mê game, yêu game thủ ở tận châu âu, chàng ta con nhà giàu, định cư rồi mà bỏ hết về vn vì nữ game thủ kia nhất mực không xuất ngoại.<br/>Cha mẹ hắn ta mừng hết lớn vì bao năm năm nỉ ko chịu về, cái chết vì gái là cái chết tê tái",
          full_name: "Thích hở hang",
          creation_time: 1610331010,
          time: "6h trước",
          userlike: 17,
          replys: { total: 1, items: [] },
          userid: 1043291719,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385142",
          parent_id: "38385142",
          article_id: 4219024,
          content:
            "Bạn chung thuỷ nhưng không đúng đối tượng rồi nè. Tỉnh lại đi bạn, có khi bạn đó là nam hoặc là giờ có chồng con rồi. Chứ ai đâu yêu 10 năm không thấy mặt lần nào. Hoặc cũng chưa hẳn bạn yêu đâu, chẳng qua bạn chưa từng gặp nên mới hiếu kỳ muốn gặp thôi, chứ gặp là vỡ mộng ngay, nói chuyện trên mạng khác ngoài đời đó.",
          full_name: "Tường Vy",
          creation_time: 1610330286,
          time: "7h trước",
          userlike: 15,
          replys: {},
          userid: 1064347077,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385118",
          parent_id: "38385118",
          article_id: 4219024,
          content:
            "Ông a đúng là thánh sống ảo luôn rồi. Nếu còn là một cậu nhóc chơi game suy nghĩ kiểu đó còn dễ chấp nhận. Đằng này hơn 30t rồi vậy mà còn hỏi câu như vậy...thôi dù sao cũng là sự lựa chọn của bản thân...cuộc đời có bao nhiêu lần 10 năm.",
          full_name: "Đặng Vũ Huy",
          creation_time: 1610330209,
          time: "7h trước",
          userlike: 14,
          replys: {},
          userid: 1039703780,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384909",
          parent_id: "38384909",
          article_id: 4219024,
          content: "Bạn ảo thật, còn người ta ảo ảo.",
          full_name: "vuvlang",
          creation_time: 1610329354,
          time: "7h trước",
          userlike: 14,
          replys: {},
          userid: 1003354479,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384800",
          parent_id: "38384800",
          article_id: 4219024,
          content:
            "Không phải anh ngây thơ mà quá ngây thơ khi giành tình yêu tới 10 năm cho một người không hề biết mặt... Có khi người yêu anh lại là một chàng trai nào đó ..!",
          full_name: "phamvanchung519",
          creation_time: 1610328893,
          time: "7h trước",
          userlike: 12,
          replys: {},
          userid: null,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385473",
          parent_id: "38385473",
          article_id: 4219024,
          content:
            "Chưa gặp mặt mà yêu nỗi gì, ông bị mơ ngủ à? Rồi giờ gặp mà người ta không đẹp như tưởng tượng rồi có yêu nữa ko?",
          full_name: "Jung eum",
          creation_time: 1610331588,
          time: "6h trước",
          userlike: 11,
          replys: {},
          userid: 1039477287,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385028",
          parent_id: "38385028",
          article_id: 4219024,
          content:
            "Sống ảo thấy ghê chưa. Xem chừng người ta đã có vợ rồi đấy.",
          full_name: "Phương Lê",
          creation_time: 1610329828,
          time: "7h trước",
          userlike: 11,
          replys: {},
          userid: 1039555848,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384862",
          parent_id: "38384862",
          article_id: 4219024,
          content:
            "Bạn ngây thơ quá, nếu cũng có tình cảm thì cổ đương nhiên muốn gặp bạn rồi chứ mắc mớ gì để bạn thất thểu mà lần nữa khước từ bí ẩn như vậy: Một là cổ chỉ hợp để nói chuyện với bạn, chơi game giải trí thế giới ảo, hai bạn ấy cũng là boy và có tính đùa zai; 2 là cổ là nữ và có quá nhiều khiếm khuyết ko tự tin gặp mặt. Nói gì thì nói bạn nên kiếm 1 cô hấp dẫn ngoài đời, còn nếu muốn rõ ràng hơn thì đưa ra tối hậu thư, nếu cổ vẫn lẩn tránh thì next đi còn kịp!",
          full_name: "bibi",
          creation_time: 1610329160,
          time: "7h trước",
          userlike: 11,
          replys: {},
          userid: null,
          type: 4,
          like_ismember: false,
        },
        {
          comment_id: "38384603",
          parent_id: "38384603",
          article_id: 4219024,
          content:
            'Nghe rất có vấn đề, ngoài 30 rồi mà suy nghĩ khờ thế nhỉ? Quen qua mạng, lại là game online bạn có biết nó có là girl thật sự không hay 1 thằng râu quai nón đang "em nè anh" để "anh ơi nạp cho em cái card này đi". Tôi đọc thấy buồn cười quá!',
          full_name: "Luân Nguyễn",
          creation_time: 1610327935,
          time: "7h trước",
          userlike: 11,
          replys: {},
          userid: 1004255060,
          type: 5,
          like_ismember: false,
        },
        {
          comment_id: "38385794",
          parent_id: "38385794",
          article_id: 4219024,
          content:
            "hậu quả của việc cắm đầu cắm cổ vào game và thế giới ảo đấy, bớt game đi, ra ngoài cff đi dạo, tán gái ở công viên thì giờ này có khi có con rồi. Tôi xưa cũng vô tình quen 1 anh trong game (năm 20 tuổi), 1 năm sau gặp mặt ngoài đời và yêu được vài tháng chính thức thì chia tay. game với gung, 30 tuổi đầu rồi, giấc mộng thanh xuân đến lúc phải tỉnh rồi.",
          full_name: "123hieuhieunguyen",
          creation_time: 1610332977,
          time: "6h trước",
          userlike: 10,
          replys: {},
          userid: 1061798172,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385110",
          parent_id: "38385110",
          article_id: 4219024,
          content:
            "Cũng may là chưa bị lừa tiền, em nào đó hãy tha cho tác giả đi đừng tạo nghiệp nữa!",
          full_name: "Huynh van Trong",
          creation_time: 1610330159,
          time: "7h trước",
          userlike: 9,
          replys: {},
          userid: 1026791353,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385270",
          parent_id: "38385270",
          article_id: 4219024,
          content:
            "30 rồi vẫn còn trẻ con. Nên cô gái ảo ko yêu ko lập gđ với chú là đúng rồi. Chưa gặp mặt mà dám đợi 10 năm. Thiên tình sử chăng?",
          full_name: "Dương Gia Huy",
          creation_time: 1610330753,
          time: "7h trước",
          userlike: 7,
          replys: {},
          userid: 1039818494,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385729",
          parent_id: "38385729",
          article_id: 4219024,
          content: "botay thanh niên, bạn hơi thiếu thực tế rồi.",
          full_name: "Bui Viet Linh",
          creation_time: 1610332722,
          time: "6h trước",
          userlike: 5,
          replys: {},
          userid: 1002632213,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384665",
          parent_id: "38384665",
          article_id: 4219024,
          content: "Ngôn tình như phim không có đâu e ! Tỉnh lại đi",
          full_name: "Phiêu du",
          creation_time: 1610328226,
          time: "7h trước",
          userlike: 4,
          replys: {},
          userid: 1041591649,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387232",
          parent_id: "38387232",
          article_id: 4219024,
          content:
            "Buồn cười quá. Ngày xưa chơi game online mình vẫn thường lấy tên con gái và sử dụng ảnh đại diện là ảnh của mấy cô ca sỹ Hàn Quốc để thả thính. Rất hiệu nghiệm nhé, các anh cúng đồ liên tục. Nếu chủ thớt đây là nạn nhân thì vô cùng xin lỗi nhé",
          full_name: "Kachiusa",
          creation_time: 1610339992,
          time: "4h trước",
          userlike: 3,
          replys: {},
          userid: 1026073967,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384758",
          parent_id: "38384758",
          article_id: 4219024,
          content:
            "Bạn bị rảnh á! Nhiều khi cô ấy là nam không chừng... Hoặc người ta có ng yêu/ko muốn tiến xa với bạn mới từ chối gặp (yêu nhau khi nào ko hay là đâu có ai nhận làm người yêu của bên còn lại đâu?) ! 30 rồi bớt mộng mơ lại đi bạn à...",
          full_name: "Thanh",
          creation_time: 1610328732,
          time: "7h trước",
          userlike: 3,
          replys: {},
          userid: 1061438315,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384738",
          parent_id: "38384738",
          article_id: 4219024,
          content: "Nên gọi anh là Mr Ảo của thập niên.",
          full_name: "Lucky",
          creation_time: 1610328605,
          time: "7h trước",
          userlike: 3,
          replys: {},
          userid: 1014411058,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385692",
          parent_id: "38385692",
          article_id: 4219024,
          content:
            "30t đã chín chắn lắm rồi, đã có thể có một gia đình đầm ấm và sự nghiệp. Nếu bạn đã thường xuyên chuyển tiền thì bạn sao kê lại rồi ra CA trình báo, đảm bảo bạn gặp được cả họ hàng nhà em trai đó luôn. 31t rồi, game ít thôi.",
          full_name: "DragonsKing",
          creation_time: 1610332522,
          time: "6h trước",
          userlike: 2,
          replys: {},
          userid: 1038956745,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385659",
          parent_id: "38385659",
          article_id: 4219024,
          content:
            "Vô phương với trai này. 10 năm mà chưa từng tìm gặp mà cũng thương yêu, lại còn từ chối người thật vì người ảo. Thôi em trai cứ chơi game, cưới vợ sinh con trên game online nhé!",
          full_name: "nguyenthanh311271",
          creation_time: 1610332393,
          time: "6h trước",
          userlike: 2,
          replys: {},
          userid: 1043750090,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384795",
          parent_id: "38384795",
          article_id: 4219024,
          content: "Tỉnh dậy đi ông, sống ảo vừa thôi ...",
          full_name: "Trang",
          creation_time: 1610328881,
          time: "7h trước",
          userlike: 2,
          replys: {},
          userid: null,
          type: 4,
          like_ismember: false,
        },
        {
          comment_id: "38384778",
          parent_id: "38384778",
          article_id: 4219024,
          content:
            "Nếu theo như bạn nói chắc giờ em đó 1 chồng và 3 con rồi bạn, đen thôi đỏ còn lâu nha :'(",
          full_name: "Toàn Phạm",
          creation_time: 1610328815,
          time: "7h trước",
          userlike: 2,
          replys: {},
          userid: 1055244464,
          type: 5,
          like_ismember: false,
        },
        {
          comment_id: "38384757",
          parent_id: "38384757",
          article_id: 4219024,
          content:
            "1 là bạn đó có GD, 2 là bạn đó là nam không phải nữ, thôi dứt khoát để tìm người yêu mới đê, nhiều khi không biết sự thật còn vui hơn!",
          full_name: "DANG NHUT",
          creation_time: 1610328718,
          time: "7h trước",
          userlike: 2,
          replys: {},
          userid: 1014622630,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384751",
          parent_id: "38384751",
          article_id: 4219024,
          content: "Ông ở đâu tôi đến gọi thức dậy, mơ lâu thế",
          full_name: "the anh pham",
          creation_time: 1610328676,
          time: "7h trước",
          userlike: 2,
          replys: {},
          userid: 1003880410,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384639",
          parent_id: "38384639",
          article_id: 4219024,
          content:
            "Bạn cần thời gian để thật sự trưởng thành rồi mới yêu đương người khác nha!",
          full_name: "Lucky flowers",
          creation_time: 1610328121,
          time: "7h trước",
          userlike: 2,
          replys: {},
          userid: 1055678778,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384618",
          parent_id: "38384618",
          article_id: 4219024,
          content:
            "Có một điều em chưa bao giờ để tôi biết mặt qua ảnh hay khi online... Người đó là AI AI AI AI? (AI:trí thông minh nhân tạo chứ không phải ai nhé!)",
          full_name: "Tò",
          creation_time: 1610327994,
          time: "7h trước",
          userlike: 2,
          replys: {},
          userid: null,
          type: 4,
          like_ismember: false,
        },
        {
          comment_id: "38389026",
          parent_id: "38389026",
          article_id: 4219024,
          content: "Trời...Có tin được không?",
          full_name: "Vicky",
          creation_time: 1610351155,
          time: "1h trước",
          userlike: 1,
          replys: {},
          userid: 1014099250,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38387781",
          parent_id: "38387781",
          article_id: 4219024,
          content:
            "Phong bạn là 'hiệp sĩ ảo mộng của năm', nhanh thoát ảo, 30 xuân xanh rồi.",
          full_name: "Hằng thu",
          creation_time: 1610343015,
          time: "3h trước",
          userlike: 1,
          replys: {},
          userid: null,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387762",
          parent_id: "38387762",
          article_id: 4219024,
          content: 'Xem chừng " cô gái " đó giờ có vợ con rồi cũng nên. Kkk',
          full_name: "bangvsmart",
          creation_time: 1610342926,
          time: "3h trước",
          userlike: 1,
          replys: {},
          userid: 1047291156,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38386450",
          parent_id: "38386450",
          article_id: 4219024,
          content:
            "Khi em đang yêu một người thì trí não sẽ tạo ra một thế giới rất tuyệt vời cho em, từ sự hợp nhau trong cách nói chuyện, chia sẻ qua các dòng tin nhắn mỗi ngày, dần dần tâm trí em sẽ bị não bộ đưa vào một thế giới như mơ về người con gái mình đang mong chờ, và cái mấu chốt là người con gái đó chưa bao giờ để em biết mặt, thì đây cũng sẽ là vực thẳm hay cơn ác mộng trong giấc mơ em đang đắm chìm. Khuyên em một câu thôi: xóa hết mọi thứ liên quan đến cô gái kia. Xóa tất cả mọi thứ, cho dù đó là tài khoản FB,.... cuộc đời em khi đó mới có thể bước sang trang mới.",
          full_name: "Phan Văn Thuật",
          creation_time: 1610336102,
          time: "5h trước",
          userlike: 1,
          replys: {},
          userid: 1006094916,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38386384",
          parent_id: "38386384",
          article_id: 4219024,
          content: "đúng vậy. quá là ngây thơ mơ mộng",
          full_name: "Nguyễn Hiền",
          creation_time: 1610335755,
          time: "5h trước",
          userlike: 1,
          replys: {},
          userid: null,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38386276",
          parent_id: "38386276",
          article_id: 4219024,
          content:
            'Câu chuyện cổ tích "người đẹp trong tranh" là có thật ở thời đại 4.0 hay sao?',
          full_name: "Ong Bầu",
          creation_time: 1610335261,
          time: "5h trước",
          userlike: 1,
          replys: {},
          userid: 1057084445,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385705",
          parent_id: "38385705",
          article_id: 4219024,
          content:
            "Hiểu luôn....<br/>Có lẽ trai giả gái nếu mà gái thật chắc cũng vài đứa con rồi quá. Tỉnh đi ông chưa biết mặt đi yêu 10 năm",
          full_name: "thanh nguyen",
          creation_time: 1610332584,
          time: "6h trước",
          userlike: 1,
          replys: {},
          userid: 1032384767,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385693",
          parent_id: "38385693",
          article_id: 4219024,
          content:
            "Tất cả chúng ta ai cũng đều có 1 'đời sống ảo' mà đã gọi là ảo thì cứ để nó trong thế giới ảo thôi,cứ coi như e đã lập gia đình vs cô gái ảo đó đi.Chứ mà cố lôi nó ra hiện thực đôi khi cô gái đó lại biến thành 1 chàng trai í",
          full_name: "A2cr",
          creation_time: 1610332536,
          time: "6h trước",
          userlike: 1,
          replys: {},
          userid: 1054870793,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385628",
          parent_id: "38385628",
          article_id: 4219024,
          content:
            "Đúng là chỉ có đàn ông mới hiểu nhau từ câu nói, sở thích, suy nghĩ. Mình nghĩ bạn không lãng phí 10 năm đâu, chẳng qua ở thực tại bạn chưa gặp đúng người khiến bạn yêu thật sự. Mà tôi nể cái người đã khiến ông yêu cả 10 năm chỉ qua tin nhắn, trong khi người tôi gặp mỗi ngày còn chẳng thèm đoái hoài đến mình.",
          full_name: "Cá kho tộ",
          creation_time: 1610332238,
          time: "6h trước",
          userlike: 1,
          replys: {},
          userid: 1064304381,
          type: 1,
          like_ismember: false,
        },
        {
          comment_id: "38385543",
          parent_id: "38385543",
          article_id: 4219024,
          content:
            "Đơn giản bởi vì đó k phải phụ nữ hoặc nếu như đã nc trực tiếp qua đt thì có thể người ta chỉ quen bạn cho vui thôi.hãy trở về thực tại đi bạn yêu cái nỗi gì khi mà cái mặt còn chưa biết.",
          full_name: "oanhpham.250988",
          creation_time: 1610331882,
          time: "6h trước",
          userlike: 1,
          replys: {},
          userid: 1033564237,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38385068",
          parent_id: "38385068",
          article_id: 4219024,
          content: "bạn hơn tôi 10 tuổi :)",
          full_name: "dinhthevinh22699",
          creation_time: 1610329983,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1062097365,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384828",
          parent_id: "38384828",
          article_id: 4219024,
          content:
            "30t rồi và đã đc 10 năm bạn vẫn ko thể xđ đc đó là cái gì, vẫn hỏi mn là bạn có ngây thơ ko thì tôi nghĩ bạn nên chờ cô ấy thêm 10 năm nữa để có câu trả lời chính xác cho mình và cô ấy. Vì 10 năm hiện nay là khoảng thời gian chưa đủ thì bạn cần chờ thêm cho đến khi nào đủ.",
          full_name: "Thu7757",
          creation_time: 1610329018,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1005054545,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384771",
          parent_id: "38384771",
          article_id: 4219024,
          content:
            "Cái này có thiệt hông vậy? Thôi đủ rồi anh, làm ơn tắt máy tính thoát ra ngoài đời thật đi cho bản thân được nhờ.",
          full_name: "Oceania",
          creation_time: 1610328780,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1054609039,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384770",
          parent_id: "38384770",
          article_id: 4219024,
          content: "Bây giờ chắc bạn ý đã có chồng con đùm đề rồi.",
          full_name: "Mẹ Sóc",
          creation_time: 1610328775,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1003070924,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384701",
          parent_id: "38384701",
          article_id: 4219024,
          content:
            "Người ấy là ai ai ai ai?<br/>Có khi là zai nên ko gặp chủ thớt",
          full_name: "Người Lạ",
          creation_time: 1610328405,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1064246150,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38384653",
          parent_id: "38384653",
          article_id: 4219024,
          content:
            'Gởi tác giả, việc chơi game nam giả trang thành nhân vật " nữ ", nói những lời nói y như "nữ" là ko hiếm, nhiều khi đó chỉ là sở thích của họ . Theo kinh nghiệm chơi game online của mình thì có ít nhất 95-100% là nam giả trang thành nữ , do đó bạn hãy quay về cuộc sống hiện tại quên đi từng dòng chat tình cảm mà bạn cùng nv nữ trong game trò chuyện . Vì ko thấy mặt của nhau cho nên đa phần những câu chat mang ý tứ tình cảm do mình tưởng ra mà thôi .',
          full_name: "longdinhq120385",
          creation_time: 1610328160,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1050664939,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38384636",
          parent_id: "38384636",
          article_id: 4219024,
          content:
            "Trong khi chơi game online với bạn có thể cô ấy đang là mẹ của vài đứa con rồi đấy bạn. Bạn hãy tìm kiếm với những cô gái ngoài đời thực đi thôi",
          full_name: "Vsa",
          creation_time: 1610328095,
          time: "7h trước",
          userlike: 1,
          replys: {},
          userid: 1007199950,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38389323",
          parent_id: "38389323",
          article_id: 4219024,
          content:
            "Chồng mình có nhiều chơi game có nhiều nick lắm.có nick thì giả làm gái.nói chuyện dẻo mồm tí là bọn con trai nạp thẻ cho.sao bạn khờ quá vậy.tin vào 1 người chưa gặp mặt",
          full_name: "Huệ",
          creation_time: 1610353325,
          time: "45' trước",
          userlike: 0,
          replys: {},
          userid: 1059714858,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38389141",
          parent_id: "38389141",
          article_id: 4219024,
          content:
            "Gặp mặt trong game rồi, kết hôn luôn trong game chắc em đồng ý đấy",
          full_name: "Thịnh Vũ",
          creation_time: 1610351989,
          time: "1h trước",
          userlike: 0,
          replys: {},
          userid: 1002813327,
          type: 5,
          like_ismember: false,
        },
        {
          comment_id: "38389113",
          parent_id: "38389113",
          article_id: 4219024,
          content:
            'Nạp hết bao nhiêu tiền game cho "cậu ấy" rồi thì khai ra, anh em hỗ trợ tìm nó đòi lại giùm cho!',
          full_name: "Nguyễn Văn Liêm",
          creation_time: 1610351805,
          time: "1h trước",
          userlike: 0,
          replys: {},
          userid: 1045093894,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38388982",
          parent_id: "38388982",
          article_id: 4219024,
          content: "Cô gái này ác thật tội nghiệp mối tình online",
          full_name: "Tu ma y",
          creation_time: 1610350843,
          time: "1h trước",
          userlike: 0,
          replys: {},
          userid: 1051818389,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38388778",
          parent_id: "38388778",
          article_id: 4219024,
          content:
            "Anh hơn e 2 tuổi tình cảm của anh bắt đầu từ một giấc mơ khi bản thân 12 tuổi nhớ cô ấy với tất cả kỹ niệm giống như sống thêm một đời và đạo của mình từ đó luôn tìm kiếm ngồi thiền luyện đạo chỉ vậy nhưng sau này lại từ bỏ duyên phận vốn không thuộc về mình cuộc đời của anh vốn đã bắt đầu một kiếp một đời với người đó có lẽ đời đó ký ức của anh với cô ấy chỉ mình anh giữ cho riêng mình",
          full_name: "Duy",
          creation_time: 1610349511,
          time: "1h trước",
          userlike: 0,
          replys: {},
          userid: 1016289215,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38388667",
          parent_id: "38388667",
          article_id: 4219024,
          content:
            "ông ơi là ông, tôi xin ông, chơi game lấy giới tính là nữ để dễ xin đồ ingame đó ông, giờ mà còn ngồi đó tơ tưởng.",
          full_name: "Atula",
          creation_time: 1610348841,
          time: "2h trước",
          userlike: 0,
          replys: {},
          userid: 1034086652,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38388494",
          parent_id: "38388494",
          article_id: 4219024,
          content:
            "Nếu là thật thì ở trỏng em nó có 3 con rồi đó. Ngồi đó mà sống ảo",
          full_name: "Vu Ha",
          creation_time: 1610347779,
          time: "2h trước",
          userlike: 0,
          replys: {},
          userid: 1033862502,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38388189",
          parent_id: "38388189",
          article_id: 4219024,
          content:
            "Tỉnh ra đi bạn ơi . Hãy dành thời gian lo cho sự nghiệp và hạnh phúc cho bản thân mình. Chạy theo tiếng gọi từ thế giới ảo thì 20-30 năm nữa cũng chả có gì cả.",
          full_name: "Minh Minh",
          creation_time: 1610345927,
          time: "2h trước",
          userlike: 0,
          replys: {},
          userid: 1049312259,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38387991",
          parent_id: "38387991",
          article_id: 4219024,
          content:
            'Đúng là bạn "đã quá ngây thơ khi tin tưởng và dành tình cảm cho một người quá lâu như vậy", có khi không phải là em nào mà là một "đực rựa" bỡn cợt bạn thôi. Ngây thơ những 10 năm thì gọi là ngây ngô cũng không sai. Ngoài 30 tuổi thì bạn vẫn còn nhiều cơ hội để tìm thấy hạnh phúc đích thực. Bạn không nên yêu qua mạng, hãy tìm những cô gái trong cơ quan hay quanh vùng bạn đang sống. Tìm thận trọng nhưng nhanh lên, bạn mất những 10 yêu ảo, tiếc thật đấy.',
          full_name: "Nguyen Kim Thanh",
          creation_time: 1610344279,
          time: "3h trước",
          userlike: 0,
          replys: {},
          userid: 1021088377,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38387705",
          parent_id: "38387705",
          article_id: 4219024,
          content:
            "Zời ạ, người ta gặp mặt nhau, yêu nhau thì còn nói chuyện đợi chờ. Còn đằng này bác ảo tưởng từ a đến z. Mà thường ảo tưởng nó đẹp lắm vì bác muốn tưởng tượng gì cũng được, ko gặp chướng ngại.<br/>Xin bác hãy thương thân bác. Một người thương mình làm gì có chuyện ko muốn gặp mặt nhau gần chục năm. Giờ bác chốt lại, một là chịu gặp bác, ko thì bác cắt đứt hết mọi liên lạc đi. Sống chi mà khổ vậy rồi than.",
          full_name: "Thanh Đình",
          creation_time: 1610342616,
          time: "3h trước",
          userlike: 0,
          replys: {},
          userid: 1051935499,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38387682",
          parent_id: "38387682",
          article_id: 4219024,
          content:
            "Nể cái vụ dành 10 năm ròng rã chỉ để đuổi theo một cái bóng. Mong sao bạn tỉnh cơn mê sớm nhất có thể.",
          full_name: "Wind",
          creation_time: 1610342455,
          time: "3h trước",
          userlike: 0,
          replys: {},
          userid: 1048871023,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387667",
          parent_id: "38387667",
          article_id: 4219024,
          content:
            "Bỏ đi anh ơi! Việc gì cũng có giới hạn của nó. Anh đã nhận thức đc 10 năm thanh xuân trôi qua vô nghĩa. Thì bây giờ nên chấm dứt và tìm lại cuộc sống thực tế hơn. Chúc a sớm vượt qua và may mắn tìm đc người mới yêu thương anh hơn...",
          full_name: "Tiểu Mi",
          creation_time: 1610342367,
          time: "3h trước",
          userlike: 0,
          replys: {},
          userid: null,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387602",
          parent_id: "38387602",
          article_id: 4219024,
          content:
            'Ra đây cùng nhảy Audition nè bạn ơi. Bớt suy nghĩ viễn vong lại đi! Bạn có biết bây giờ cô ấy đã đi lấy chồng rồi chưa? Nếu chưa thì nghe "Lý Cây Bông" thì sẽ rõ .',
          full_name: "Tuan Kiet",
          creation_time: 1610341980,
          time: "3h trước",
          userlike: 0,
          replys: {},
          userid: 1006895883,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38387568",
          parent_id: "38387568",
          article_id: 4219024,
          content: "Nhìn mặt chắc vỡ mộng luôn",
          full_name: "mchkp2000",
          creation_time: 1610341733,
          time: "3h trước",
          userlike: 0,
          replys: {},
          userid: 1049126534,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38387535",
          parent_id: "38387535",
          article_id: 4219024,
          content:
            "Anh đúng là cây si lạ hiếm có. Nếu cảm xúc như anh chắc chỉ có hồi tụi em chat chit yahoo hồi xưa á... Thôi anh nên đi lấy vợ và xem như kỷ niệm vui đi. Chúc anh thăng bằng trở lại.",
          full_name: "Meowmeow",
          creation_time: 1610341596,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1053935483,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387502",
          parent_id: "38387502",
          article_id: 4219024,
          content: "bạn đợi thêm 10 năm nữa xem sao",
          full_name: "Anh Sao Xanh",
          creation_time: 1610341377,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1064006334,
          type: 5,
          like_ismember: false,
        },
        {
          comment_id: "38387445",
          parent_id: "38387445",
          article_id: 4219024,
          content: "Sống ảo, hậu quả thật là đây!",
          full_name: "vuhungcuong1965",
          creation_time: 1610341088,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1055383558,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387059",
          parent_id: "38387059",
          article_id: 4219024,
          content:
            "Đời như một trò chơi bạn ko nghe ng ta nói thế à mau mà lấy v đi ko già queo bây giờ",
          full_name: "mimoza",
          creation_time: 1610339080,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1011522775,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38387017",
          parent_id: "38387017",
          article_id: 4219024,
          content: "Game Over đi bạn. Người ấy là con trai nhé",
          full_name: "quanghung14121972",
          creation_time: 1610338871,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1059726451,
          type: 6,
          like_ismember: false,
        },
        {
          comment_id: "38386953",
          parent_id: "38386953",
          article_id: 4219024,
          content:
            "Phải nói là là ... thật ko thể tin nổi. Tui hồi xưa cũng có cái trò làm quen trên mạng nhưng khi hẹn ra gặp mặt thì thì chả ra làm sao cả. Có lần nó dắt theo vài tên xăm trổ nhìn muốn hoảng hồn (tui cẩn thận lắm, nhận diện e nó từ xa trc chứ ko để e nhận diện mình trc). Lại có lần nhìn như anh chị thứ thiệt, ... Từ đó bỏ luôn cái vụ làm quen trên mạng. Cứ đời thực mà tính cho bảo đảm, ko khéo có ngày trao mạng cho đầu trộm đuôi cướp thì có mà tàn đời. Nhớ nha e trai",
          full_name: "Tú Anh",
          creation_time: 1610338609,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1034787360,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38386912",
          parent_id: "38386912",
          article_id: 4219024,
          content: '"game thủ" có khác kha kha...',
          full_name: "STEED400",
          creation_time: 1610338451,
          time: "4h trước",
          userlike: 0,
          replys: {},
          userid: 1013684275,
          type: 8,
          like_ismember: false,
        },
        {
          comment_id: "38385369",
          parent_id: "38385369",
          article_id: 4219024,
          content:
            "Bạn thật sự là một người sống ảo, hãy nhảy ra khỏi mạng ảo và sống cuộc đời thực, mạng xã hội chỉ kết nối thời gian đầu, sau đó là người thật việc thật, nếu không kết nối được đó chính là ảo, hãy đến với một cô gái khác thiết thực hơn.",
          full_name: "huyhoangphamdt595",
          creation_time: 1610331153,
          time: "6h trước",
          userlike: 0,
          replys: {},
          userid: 1051157043,
          type: 6,
          like_ismember: false,
        },
      ],
      offset: 0,
    },
  },
};
export const replies = {
  error: 0,
  errorDescription: "",
  data: {
    data: {
      items: [
        {
          comment_id: "38385481",
          parent_id: 38384616,
          article_id: 4219024,
          content:
            "Đúng là vùi đầu vào game làm mất hẳn kỹ năng giao tiếp và kiến thức xã hội!",
          full_name: "KAMAZ",
          creation_time: 1610331623,
          time: "09:20 11/1",
          userlike: 50,
          like_ismember: false,
          userid: 1032237792,
          type: 8,
        },
        {
          comment_id: "38386390",
          parent_id: 38384616,
          article_id: 4219024,
          content: "Nghiện game mà đi làm còn đi công tác các kiểu hả bạn.?",
          full_name: "Đào Xuân Thành",
          creation_time: 1610335795,
          time: "10:29 11/1",
          userlike: 9,
          like_ismember: false,
          userid: 1005087453,
          type: 8,
        },
        {
          comment_id: "38386460",
          parent_id: 38384616,
          article_id: 4219024,
          content:
            '<span class="reply_name myuser" data-userid="1005087453">@Đào Xuân Thành</span>:&nbsp;Chuyện đi công tác hay đi làm đâu liên quan đến suy nghĩ ảo tưởng về tình cảm, xa rời thực tế đâu bạn.',
          full_name: "Ben",
          creation_time: 1610336155,
          time: "10:35 11/1",
          userlike: 33,
          like_ismember: false,
          userid: 1049099077,
          type: 8,
        },
      ],
    },

    offset: 0,
    parent_id: 38384616,
  },
};
